# Generated by Django 4.0.4 on 2022-04-22 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ER_Game_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('season', models.CharField(default=0, max_length=10)),
                ('rank', models.IntegerField()),
                ('matchingMode', models.CharField(max_length=10)),
                ('matchingTeamMode', models.CharField(max_length=10)),
                ('character', models.CharField(max_length=50)),
                ('characterlevel', models.IntegerField(default=1)),
                ('bestWeapon', models.CharField(max_length=30)),
                ('bestWeaponLevel', models.IntegerField(default=1)),
                ('Kills', models.FloatField(null=True)),
                ('Hunts', models.FloatField(null=True)),
                ('Assistants', models.FloatField(null=True)),
                ('mmr', models.IntegerField(default=0, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ER_Stats_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=30, null=True)),
                ('matchingMode', models.CharField(max_length=10)),
                ('matchingTeamMode', models.CharField(max_length=10)),
                ('season', models.CharField(default=0, max_length=10)),
                ('character', models.CharField(max_length=50)),
                ('lavel', models.IntegerField(default=1)),
                ('bestWeapon', models.CharField(max_length=30)),
                ('survivalTime', models.IntegerField(null=True)),
                ('averagerank', models.IntegerField(null=True)),
                ('averageKills', models.FloatField(null=True)),
                ('averageHunts', models.FloatField(null=True)),
                ('averageAssistants', models.FloatField(null=True)),
                ('averageDeal', models.FloatField(null=True)),
                ('averageProficiency', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('mmr', models.IntegerField(default=0, null=True)),
                ('averagebestWeaponLevel', models.IntegerField(null=True)),
                ('averageTraplevel', models.IntegerField(null=True)),
                ('averageProductionlevel', models.IntegerField(null=True)),
                ('averageSearchlevel', models.IntegerField(null=True)),
                ('averageMovelevel', models.IntegerField(null=True)),
                ('averageStrengthlevel', models.IntegerField(null=True)),
                ('averageDefenselevel', models.IntegerField(null=True)),
                ('averageHuntinglevel', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ER_User_Info_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('most_pick', models.JSONField(default='{}')),
                ('mmr', models.IntegerField(default=0, null=True)),
                ('averagerank', models.FloatField(null=True)),
                ('averageKills', models.FloatField(null=True)),
                ('averageHunts', models.FloatField(null=True)),
                ('averageAssistants', models.FloatField(default=0, null=True)),
                ('averageDeal', models.FloatField(null=True)),
                ('averageProficiency', models.FloatField(null=True)),
                ('soloTier', models.CharField(default='Unrank', max_length=15, null=True)),
                ('duoTier', models.CharField(default='Unrank', max_length=15, null=True)),
                ('squadTier', models.CharField(default='Unrank', max_length=15, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mastery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery', to='api.mastery')),
            ],
        ),
    ]
