# Generated by Django 4.0.4 on 2022-04-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='er_base_model',
            name='averageDeal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='er_base_model',
            name='averageHunts',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='er_base_model',
            name='averageKills',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='er_base_model',
            name='averageProficiency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='er_base_model',
            name='winning_rate',
            field=models.FloatField(null=True),
        ),
    ]
