# Generated by Django 4.0.4 on 2022-04-18 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='er_user_info_model',
            name='averageAssistants',
            field=models.FloatField(null=True),
        ),
    ]
