# Generated by Django 4.0.4 on 2022-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='er_game_record_model',
            name='character',
        ),
        migrations.AddField(
            model_name='er_game_record_model',
            name='charnum',
            field=models.IntegerField(null=True),
        ),
    ]
