# Generated by Django 4.0.4 on 2022-04-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostpick',
            old_name='most_one_char',
            new_name='most_one_charImage',
        ),
        migrations.AddField(
            model_name='mostpick',
            name='most_one_charName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
