# Generated by Django 4.0.4 on 2022-05-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='er_user_info_model',
            old_name='averageRank',
            new_name='averageRanking',
        ),
    ]
