# Generated by Django 4.0.4 on 2022-04-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='er_user_info_model',
            name='mmr',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='er_game_record',
            name='mmr',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='mmr',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
