# Generated by Django 4.0.4 on 2022-05-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='er_user_info_model',
            name='matchingTeamMode',
            field=models.IntegerField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='er_user_info_model',
            name='season',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='er_stats_model',
            name='matchingTeamMode',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
