# Generated by Django 4.0.4 on 2022-05-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_er_user_info_model_matchingteammode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='er_user_info_model',
            old_name='season',
            new_name='seasonId',
        ),
    ]
