# Generated by Django 4.0.4 on 2022-05-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_er_game_record_model_character_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='charName',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='charnum',
            field=models.IntegerField(null=True),
        ),
    ]
