# Generated by Django 4.0.4 on 2022-04-23 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_most_one_char_mostpick_most_one_charimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='er_game_record',
            name='items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itemmodels'),
        ),
        migrations.AlterField(
            model_name='mostpick',
            name='most_one_charImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
