# Generated by Django 4.0.4 on 2022-04-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_er_base_model_duotier_er_base_model_squadtier_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ER_Game_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
                ('season', models.CharField(default=0, max_length=10)),
                ('lavel', models.IntegerField(default=1)),
                ('character', models.CharField(max_length=50)),
                ('Kills', models.FloatField(null=True)),
                ('Hunts', models.FloatField(null=True)),
                ('Assistants', models.FloatField(null=True)),
                ('mmr', models.IntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
