# Generated by Django 4.0.4 on 2022-05-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_averagerank_er_stats_model_averageranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='er_stats_model',
            name='averageItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.itemmodel'),
        ),
        migrations.AlterField(
            model_name='er_stats_model',
            name='averageTrait',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.traitmodel'),
        ),
    ]
