# Generated by Django 4.0.4 on 2022-05-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_itemmodel_charname_itemmodel_charnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='er_game_record_model',
            name='bestWeapon',
            field=models.IntegerField(null=True),
        ),
    ]
