# Generated by Django 4.0.4 on 2022-05-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_season_er_user_info_model_seasonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='er_user_info_model',
            name='seasonId',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
