# Generated by Django 4.0.4 on 2022-05-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_er_game_record_model_trait'),
    ]

    operations = [
        migrations.AddField(
            model_name='er_game_record_model',
            name='gameId',
            field=models.IntegerField(null=True),
        ),
    ]
