# Generated by Django 4.0.4 on 2022-05-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_er_game_record_model_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mostpickmodel',
            name='matchingTeamMode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
