# Generated by Django 4.0.4 on 2022-05-12 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_mostpickmodel_matchingteammode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_three_char',
        ),
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_two_char',
        ),
        migrations.AddField(
            model_name='mostpickmodel',
            name='most_three_charName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mostpickmodel',
            name='most_two_charName',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
