# Generated by Django 4.0.4 on 2022-05-13 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_mostpickmodel_most_three_char_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_one_charImage',
        ),
    ]
