# Generated by Django 4.0.4 on 2022-05-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_mostpickmodel_most_three_char_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_one_charImage',
        ),
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_one_charName',
        ),
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_three_charName',
        ),
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_two_charName',
        ),
        migrations.AddField(
            model_name='mostpickmodel',
            name='most_one_charcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mostpickmodel',
            name='most_three_charcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mostpickmodel',
            name='most_two_charcode',
            field=models.IntegerField(null=True),
        ),
    ]
