# Generated by Django 4.0.4 on 2022-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_er_user_info_model_matchingteammode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_one_averageRank',
        ),
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_three_averageRank',
        ),
        migrations.RemoveField(
            model_name='mostpickmodel',
            name='most_two_averageRank',
        ),
        migrations.AlterField(
            model_name='mostpickmodel',
            name='matchingTeamMode',
            field=models.IntegerField(null=True),
        ),
    ]
